### ISSUE TITLE
フィールドネームがnameの時にフォーム送信ができない

### ISSUE THREAD

**Issue by t-fukui** [oiax/capejs#8]
component.jsの_Internal#serializeFormsのメソッドでif (forms[i].name)と条件分岐で書いてあるのだが、field nameがnameだと通過してしまう。
例えば、memberモデルがあってカラム名がnameだとデータの登録、更新ができない

**Comment by kuroda** [comment]
確認しました。直します。

**Comment by kuroda** [comment]
Fixed by https://github.com/oiax/capejs/commit/88069b79d26c04c80eafd33fe90e7151834ddbc4.

Please use `v0.10.1`.
